version: "3"
services:
  api_dev:
    image: gabrielmotroni/apinewsredis
    ports:
      - "5001:3050"
    links:
      - link-db
  link-db:
    image: tutum/mongodb
    ports:
      - "27017:27017"
      - "28017:28017"
    environment:
      - AUTH=no
  redis:
    image: "redis"
